
####                                              ####
# In this workflow we run all the examples           #
# This should always be up-to-date with the examples #
####                                              ####
name: Examples
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.dropLockfile && ' (drop lockfile)' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-22.04
          - windows-latest
        dropLockfile:
          - true
          - false

    steps:
    - uses: actions/checkout@v4

    - name: worker_pool
      run: cargo run --example worker_pool --features "worker"

    - name: web_features
      run: cargo run --example web_features --features "web"

    - name: url_imports
      run: cargo run --example url_import --features="fs_import url_import"

    - name: typescript_modules
      run: cargo run --example typescript_modules

    - name: thread_safety
      run: cargo run --example thread_safety

    - name: serialized_types
      run: cargo run --example serialized_types

    - name: runtime_extensions
      run: cargo run --example runtime_extensions

    - name: multiple_modules
      run: cargo run --example multiple_modules

    - name: module_loader_cache
      run: cargo run --example module_loader_cache

    - name: module_import
      run: cargo run --example module_import

    - name: interactive_prompt
      run: cargo run --example interactive_prompt -- 5+5

    - name: hello_world
      run: cargo run --example hello_world

    - name: functions_and_values
      run: cargo run --example functions_and_values

    - name: entrypoint_functions
      run: cargo run --example entrypoint_functions

    - name: default_threaded_worker
      run: cargo run --example default_threaded_worker --features "worker"

    - name: custom_threaded_worker
      run: cargo run --example custom_threaded_worker --features "worker"

    - name: custom_runtimes
      run: cargo run --example custom_runtimes

    - name: custom_import_logic
      run: cargo run --example custom_import_logic --features "url_import"

    - name: create_snapshot
      run: cargo run --example create_snapshot --features "snapshot_builder"

    - name: call_rust_from_js
      run: cargo run --example call_rust_from_js

    - name: async_javascript
      run: cargo run --example async_javascript

    - name: async_eval
      run: cargo run --example async_eval

    - name: websocket
      run: cargo run --example websocket --features="web websocket"
