name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.dropLockfile && ' (drop lockfile)' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-22.04
          - windows-latest
        dropLockfile:
          - true
          - false

    steps:
    - uses: actions/checkout@v4

    # Run tests with no features
    - name: Run barebones tests
      run: cargo test --no-default-features --lib

    # Run default feature tests
    - name: Run tests
      run: cargo test --verbose --lib

    # Run tests with just web feature
    - name: Run web tests
      run: cargo test --features "web" --lib

    # Run tests with all features
    - name: Run complete tests
      run: cargo test --all-features --lib
